apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"customers-service","namespace":"spring-petclinic"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"customers-service"}}}
  creationTimestamp: "2025-12-27T09:50:51Z"
  name: customers-service
  namespace: spring-petclinic
  resourceVersion: "713229"
  uid: 81baaf2a-0d07-4224-833c-dea1132063ac
spec:
  clusterIP: 10.0.54.71
  clusterIPs:
  - 10.0.54.71
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customers-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
