apiVersion: v1
data:
  password: R01pZ2x4c205TnJ0UTY3WEdYTExzdw==
  url: amRiYzpteXNxbDovL3NlcnZlcjIyODA1NjIwNC5teXNxbC5kYXRhYmFzZS5henVyZS5jb206MzMwNi9wZXRjbGluaWM/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmdXNlU1NMPXRydWUmcmVxdWlyZVNTTD1mYWxzZSZzZXJ2ZXJUaW1lem9uZT1VVEMmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZQ==
  username: bmVlZGZ1bHZlbmlzb24w
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"R01pZ2x4c205TnJ0UTY3WEdYTExzdw==","url":"amRiYzpteXNxbDovL3NlcnZlcjIyODA1NjIwNC5teXNxbC5kYXRhYmFzZS5henVyZS5jb206MzMwNi9wZXRjbGluaWM/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmdXNlU1NMPXRydWUmcmVxdWlyZVNTTD1mYWxzZSZzZXJ2ZXJUaW1lem9uZT1VVEMmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZQ==","username":"bmVlZGZ1bHZlbmlzb24w"},"kind":"Secret","metadata":{"annotations":{},"name":"mysql-secrets","namespace":"spring-petclinic"}}
  creationTimestamp: "2025-12-27T09:20:14Z"
  name: mysql-secrets
  namespace: spring-petclinic
  resourceVersion: "708199"
  uid: d3862fbb-0380-422c-8ff8-2b0acde73eb6
type: Opaque
