apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2025-12-25T19:03:57Z"
  generation: 1
  labels:
    app: azure-cns-win
    app.kubernetes.io/managed-by: Eno
    kubernetes.azure.com/managedby: aks
  name: azure-cns-win
  namespace: kube-system
  resourceVersion: "468"
  uid: ab25dfa9-4ddd-4b87-8c6f-3451f27a2094
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: azure-cns-win
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
        kubernetes.azure.com/azure-cns-configmap-checksum: 976a0148778e53aa0074cc8cc4e64d113daf8bf44ba9dbdacc808b2d1e4e0cb2
        prometheus.io/port: "10092"
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Eno
        k8s-app: azure-cns-win
        kubernetes.azure.com/managedby: aks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - windows
      containers:
      - args:
        - .\azure-cns.exe
        - -c
        - tcp://$(CNSIpAddress):$(CNSPort)
        - -t
        - $(CNSLogTarget)
        - -o
        - $(CNSLogDir)
        - -storefilepath
        - $(CNSStoreFilePath)
        - -config-path
        - '%CONTAINER_SANDBOX_MOUNT_POINT%\$(CNS_CONFIGURATION_PATH)'
        command:
        - powershell.exe
        env:
        - name: PATH
          value: '%CONTAINER_SANDBOX_MOUNT_POINT%\Windows\System32\WindowsPowershell\v1.0\'
        - name: CNSIpAddress
          value: 127.0.0.1
        - name: CNSPort
          value: "10090"
        - name: CNSLogTarget
          value: stdoutfile
        - name: CNSLogDir
          value: /k/azurecns
        - name: CNSStoreFilePath
          value: /k/azurecns/
        - name: CNS_CONFIGURATION_PATH
          value: /etc/azure-cns/cns_config.json
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_CIDRs
          value: 10.244.0.0/16
        - name: SERVICE_CIDRs
          value: 10.0.0.0/16
        - name: INFRA_VNET_CIDRs
          value: 10.224.0.0/12
        image: mcr.microsoft.com/containernetworking/azure-cns:v1.7.9-0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cns-container
        ports:
        - containerPort: 10090
          name: api
          protocol: TCP
        - containerPort: 10092
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /readyz
            port: metrics
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
        securityContext:
          privileged: true
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /k/azurecns
          name: log
        - mountPath: /etc/azure-cns
          name: cns-config
        - mountPath: /var/run/azure-vnet
          name: azure-vnet
        workingDir: $env:CONTAINER_SANDBOX_MOUNT_POINT
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - args:
        - '%CONTAINER_SANDBOX_MOUNT_POINT%/dropgz'
        - deploy
        - --skip-verify
        - azure-vnet-stateless
        - -o
        - /k/azurecni/bin/azure-vnet.exe
        command:
        - powershell.exe
        env:
        - name: PATHEXT
          value: .EXE;;
        image: mcr.microsoft.com/containernetworking/azure-cni:v1.7.9-0
        imagePullPolicy: IfNotPresent
        name: cni-installer
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /k/azurecni/bin/
          name: cni-bin
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: NT AUTHORITY\SYSTEM
      serviceAccount: azure-cns
      serviceAccountName: azure-cns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /k/azurecns
          type: DirectoryOrCreate
        name: log
      - configMap:
          defaultMode: 420
          name: cns-win-config
        name: cns-config
      - hostPath:
          path: /var/run/azure-vnet
          type: DirectoryOrCreate
        name: azure-vnet
      - hostPath:
          path: /k/azurecni/bin
          type: DirectoryOrCreate
        name: cni-bin
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2%
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 1
