apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.azure.com/managedby":"aks","kubernetes.io/cluster-service":"true"},"name":"csi-azurefile-node-win","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"csi-azurefile-node-win"}},"template":{"metadata":{"labels":{"app":"csi-azurefile-node-win","kubernetes.azure.com/managedby":"aks"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.azure.com/cluster","operator":"Exists"},{"key":"type","operator":"NotIn","values":["virtual-kubelet"]},{"key":"kubernetes.io/os","operator":"In","values":["windows"]}]}]}}},"containers":[{"args":["--csi-address=$(CSI_ENDPOINT)","--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)","--plugin-registration-path=$(PLUGIN_REG_DIR)","--v=2"],"command":["csi-node-driver-registrar.exe"],"env":[{"name":"CSI_ENDPOINT","value":"unix://C:\\\\var\\\\lib\\\\kubelet\\\\plugins\\\\file.csi.azure.com\\\\csi.sock"},{"name":"DRIVER_REG_SOCK_PATH","value":"C:\\\\var\\\\lib\\\\kubelet\\\\plugins\\\\file.csi.azure.com\\\\csi.sock"},{"name":"PLUGIN_REG_DIR","value":"C:\\\\var\\\\lib\\\\kubelet\\\\plugins_registry\\\\"},{"name":"KUBE_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}}],"image":"mcr.microsoft.com/oss/v2/kubernetes-csi/csi-node-driver-registrar:v2.15.0","imagePullPolicy":"IfNotPresent","name":"node-driver-registrar","resources":{"limits":{"memory":"150Mi"},"requests":{"cpu":"40m","memory":"40Mi"}},"securityContext":{"capabilities":{"drop":["ALL"]}}},{"args":["--v=5","--endpoint=$(CSI_ENDPOINT)","--nodeid=$(KUBE_NODE_NAME)","--enable-windows-host-process=true"],"command":["azurefileplugin.exe"],"env":[{"name":"AZURE_CREDENTIAL_FILE","value":"C:\\k\\azure.json"},{"name":"CSI_ENDPOINT","value":"unix://C:\\\\var\\\\lib\\\\kubelet\\\\plugins\\\\file.csi.azure.com\\\\csi.sock"},{"name":"KUBE_NODE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}}],"image":"mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.33.5-windows-hp","imagePullPolicy":"IfNotPresent","name":"azurefile","securityContext":{"capabilities":{"drop":["ALL"]}}}],"hostNetwork":true,"initContainers":[{"command":["powershell.exe","-c","New-Item -ItemType Directory -Path C:\\var\\lib\\kubelet\\plugins\\file.csi.azure.com\\ -Force"],"image":"mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.33.5-windows-hp","imagePullPolicy":"IfNotPresent","name":"init","securityContext":{"capabilities":{"drop":["ALL"]}}}],"priorityClassName":"system-node-critical","securityContext":{"seccompProfile":{"type":"RuntimeDefault"},"windowsOptions":{"hostProcess":true,"runAsUserName":"NT AUTHORITY\\SYSTEM"}},"serviceAccountName":"csi-azurefile-node-sa","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}]}}}}
  creationTimestamp: "2025-12-25T19:04:31Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.azure.com/managedby: aks
    kubernetes.io/cluster-service: "true"
  name: csi-azurefile-node-win
  namespace: kube-system
  resourceVersion: "596"
  uid: 408b231d-47b0-4ed0-be83-dd2f11fc3ce4
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-azurefile-node-win
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-azurefile-node-win
        kubernetes.azure.com/managedby: aks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - windows
      containers:
      - args:
        - --csi-address=$(CSI_ENDPOINT)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --plugin-registration-path=$(PLUGIN_REG_DIR)
        - --v=2
        command:
        - csi-node-driver-registrar.exe
        env:
        - name: CSI_ENDPOINT
          value: unix://C:\\var\\lib\\kubelet\\plugins\\file.csi.azure.com\\csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: C:\\var\\lib\\kubelet\\plugins\\file.csi.azure.com\\csi.sock
        - name: PLUGIN_REG_DIR
          value: C:\\var\\lib\\kubelet\\plugins_registry\\
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: mcr.microsoft.com/oss/v2/kubernetes-csi/csi-node-driver-registrar:v2.15.0
        imagePullPolicy: IfNotPresent
        name: node-driver-registrar
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 40m
            memory: 40Mi
        securityContext:
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeid=$(KUBE_NODE_NAME)
        - --enable-windows-host-process=true
        command:
        - azurefileplugin.exe
        env:
        - name: AZURE_CREDENTIAL_FILE
          value: C:\k\azure.json
        - name: CSI_ENDPOINT
          value: unix://C:\\var\\lib\\kubelet\\plugins\\file.csi.azure.com\\csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.33.5-windows-hp
        imagePullPolicy: IfNotPresent
        name: azurefile
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - powershell.exe
        - -c
        - New-Item -ItemType Directory -Path C:\var\lib\kubelet\plugins\file.csi.azure.com\
          -Force
        image: mcr.microsoft.com/oss/v2/kubernetes-csi/azurefile-csi:v1.33.5-windows-hp
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        windowsOptions:
          hostProcess: true
          runAsUserName: NT AUTHORITY\SYSTEM
      serviceAccount: csi-azurefile-node-sa
      serviceAccountName: csi-azurefile-node-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 1
