apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"sealed-secrets-controller"},"name":"sealed-secrets-controller","namespace":"kube-system"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"name":"sealed-secrets-controller"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-27T14:43:32Z"
  labels:
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: kube-system
  resourceVersion: "819000"
  uid: 9cae5b9d-f9db-4bd4-863a-9a8be4705ff3
spec:
  clusterIP: 10.0.84.45
  clusterIPs:
  - 10.0.84.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: sealed-secrets-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
