apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"sealed-secrets-controller-metrics"},"name":"sealed-secrets-controller-metrics","namespace":"kube-system"},"spec":{"ports":[{"port":8081,"targetPort":8081}],"selector":{"name":"sealed-secrets-controller"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-27T14:43:36Z"
  labels:
    name: sealed-secrets-controller-metrics
  name: sealed-secrets-controller-metrics
  namespace: kube-system
  resourceVersion: "819042"
  uid: cd2afb7e-f459-4c57-8ec2-87c868da562c
spec:
  clusterIP: 10.0.207.158
  clusterIPs:
  - 10.0.207.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    name: sealed-secrets-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
