apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-12-27T11:41:34Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.0
    helm.sh/chart: grafana-10.4.0
  name: obs-grafana
  namespace: monitoring
  resourceVersion: "751806"
  uid: c95164c7-25b2-4543-bfcb-8ba63d6f3627
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.103.194
  clusterIPs:
  - 10.0.103.194
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30377
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.210.122.215
      ipMode: VIP
