apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: obs
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-12-27T11:11:50Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: obs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/version: 2.17.0
    helm.sh/chart: kube-state-metrics-7.0.0
    release: obs
  name: obs-kube-state-metrics
  namespace: monitoring
  resourceVersion: "741216"
  uid: 42f30261-6889-4986-976d-c5cf4ce8657b
spec:
  clusterIP: 10.0.190.254
  clusterIPs:
  - 10.0.190.254
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/name: kube-state-metrics
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
