apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/Shalinihs/spring-petclinic-cloud
  ref:
    tag: demo-jan-2025
