apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notification-controller","app.kubernetes.io/instance":"flux-system","app.kubernetes.io/part-of":"flux","control-plane":"controller"},"name":"notification-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"notification-controller"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-26T16:13:09Z"
  labels:
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    control-plane: controller
  name: notification-controller
  namespace: flux-system
  resourceVersion: "344209"
  uid: 0aa2e076-3a2a-4408-ab7e-aabcc84cc602
spec:
  clusterIP: 10.0.255.225
  clusterIPs:
  - 10.0.255.225
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
