apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"source-controller","app.kubernetes.io/instance":"flux-system","app.kubernetes.io/part-of":"flux","control-plane":"controller"},"name":"source-controller","namespace":"flux-system"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"source-controller"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-26T16:13:10Z"
  labels:
    app.kubernetes.io/component: source-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    control-plane: controller
  name: source-controller
  namespace: flux-system
  resourceVersion: "344219"
  uid: 794ab831-221b-4ee5-a9d0-42a504dd61bc
spec:
  clusterIP: 10.0.201.68
  clusterIPs:
  - 10.0.201.68
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
