apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-12-25T19:03:53Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "217"
  uid: d49fce38-a814-4dea-97d6-6eb224dd914b
spec:
  clusterIP: 10.0.0.1
  clusterIPs:
  - 10.0.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
